# ─────────────────────────────────────────────
# Configuración de la aplicación
# ─────────────────────────────────────────────
spring.application.name=biblioteca-api

# ─────────────────────────────────────────────
# Conexión a MongoDB Atlas
# ─────────────────────────────────────────────
spring.data.mongodb.uri=mongodb+srv://juancamilorose_db_user:TSTofwQer4SVKGh4@cluster0.22fkw2t.mongodb.net/biblioteca_db?retryWrites=true&w=majority

# Nombre de la base de datos en MongoDB
spring.data.mongodb.database=biblioteca_db

# ─────────────────────────────────────────────
# Servidor
# ─────────────────────────────────────────────
server.port=8080
